https://docs.github.com/de/discussions/managing-discussions-for-your-community/creating-discussion-category-forms

https://docs.github.com/de/repositories/working-with-files/managing-files/creating-new-files

https://docs.github.com/de/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms

https://docs.github.com/de/repositories/working-with-files/managing-files/creating-new-files